GUI with Zenity

diff --git a/rec_client b/rec_client
--- a/rec_client
+++ b/rec_client
@@ -2,32 +2,66 @@
 
 printf "===========================================\n\t\tSMTP MAIL SERVER\t\t\n===========================================\n"
 
-printf "Input User Name  : "
-read username
 
-printf "Input your passwd: "
-read pwd
+zenity --forms --title="Receiver Mail Authentication Console" \
+	--text="Enter required information" \
+	--separator="$" \
+	--add-entry="Your Email Address" \
+	--add-entry="Your Password" > auth.csv 2> /dev/null
+
+case $? in
+    0)
+        echo "trying to authenticate...";;
+    1)
+        echo "xx"
+	;;
+    -1)
+        echo "An unexpected error has occurred."
+	;;
+esac
+
+
+username=$(cut auth.csv -d '$' -f1)
+pwd=$(cut auth.csv -d '$' -f2)
 
 if [ "$pwd" = "1234" ]; then
-  echo ">> Auth Sucessful!"
+  
+	zenity --info \
+	--text="Authentication Sucessful" 2> /dev/null
+
   last=0
   ## inputing notification logic here
   if [ -e /tmp/mail.eml ]
 		 then 
 		 play -n -q synth 0.1 sin 880 || echo -e "\a" > /dev/null
-		 y=$(zenity   --notification  --title  "Alert"  --text "You have unread Email!")
-		 printf "Do you want to read it? y/n: "
-		 read y
-		 #echo $y
-			 if [ "$y" = "y" ]; then xterm -e "cat /tmp/mail.eml | sed '10d'; bash"
-			 enscript /tmp/mail.eml -o mail.pdf
-			 else echo "no issues!"
-			 fi
-		echo date -r package.json +%s > /tmp/new
-		last=$(cat /tmp/new) 
-	 	echo "Your mail was read by receipient" > stamp
+		 notify-send "You have new unread mail"
+			 FILE='/tmp/mail.eml'
+
+			sudo zenity --text-info \
+				   --title="Your New Mail" \
+				   --filename=$FILE  2> /dev/null
+
+			case $? in
+				0)
+					echo "Done"
+				# next step
+				;;
+				1)
+					echo "Stop"
+				;;
+				-1)
+					echo "An unexpected error has occurred."
+				;;
+			esac
+
+			 cat /tmp/mail.eml >> old_mails
+			 echo "---------------------------" >> old_mails
+			 rm /tmp/mail.eml
+
 	 else echo "No new mail!"
 	 fi
-else echo "XX Access Denied!"
+else 
+zenity --error \
+	--text="Access Denied!" 2> /dev/null
 fi
 
diff --git a/send_console b/send_console
--- a/send_console
+++ b/send_console
@@ -2,16 +2,52 @@
 
 printf "===========================================\n\t\tSMTP MAIL SERVER\t\t\n===========================================\n"
 
-printf "Sender's Email ID   : "
-read sender
-printf "Receiver's Email ID : "
-read receiver
+#printf "Sender's Email ID   : "
 
-printf "Sending Email --\n"
-swaks -h domain.com -f $sender -t $receiver --body $1 -s localhost -p 2525
+c=$(wc -l < old_mails)
+zenity --forms --title="SMTP Send Mail Console" \
+	--text="Enter required information" \
+	--separator="$" \
+	--add-entry="Your Email Address" \
+	--add-entry="Recipient's Email Address" \
+	--add-entry="Your Message "  > mbook.csv 2> /dev/null
 
+case $? in
+    0)
+        echo "trying to send mail...";;
+    1)
+        echo "No mail sent."
+	;;
+    -1)
+        echo "An unexpected error has occurred."
+	;;
+esac
+
+
+sender=$(cut mbook.csv -d '$' -f1)
+receiver=$(cut mbook.csv -d '$' -f2)
+tbody=$(cut mbook.csv -d '$' -f3)
+
+
+#echo $sender $receiver $tbody
+swaks -h domain.com -f $sender -t $receiver --body $tbody -s localhost -p 2525  > sender.log 
+
+lno=$(wc -l < sender.log)
+	if [ $lno -gt 20 ]
+	then
+	notify-send "Mail Sent to $receiver"
+	else echo "There was some trouble. 
+	Kindly check the sender.log file for details about problem"
+	fi
+## read receipts
 while [ 2 -gt 1 ]
 do
-	cat stamp;
-	#echo "at" date
+d=$(wc -l < old_mails)
+if [ $c != $d ] 
+then
+	printf "Your Mail was read by receipient $receiver at " 
+	date -r old_mails
+	break
+fi
 done;
+
